// <auto-generated />
using System;
using AlexWoW.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlexWoW.Database.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260610094259_WidenAccountUsername")]
    partial class WidenAccountUsername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AlexWoW.Database.Entities.Account", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("is_admin");

                    b.Property<string>("LastIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_ip");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("salt");

                    b.Property<byte[]>("SessionKey")
                        .HasColumnType("binary(40)")
                        .HasColumnName("session_key");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.Property<byte[]>("Verifier")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("verifier");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uk_account_username");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.AccountDataBlob", b =>
                {
                    b.Property<uint>("OwnerId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("owner_id");

                    b.Property<byte>("IsChar")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("is_char");

                    b.Property<byte>("DataType")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("data_type");

                    b.Property<byte[]>("Data")
                        .HasColumnType("longblob")
                        .HasColumnName("data");

                    b.Property<uint>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("update_time");

                    b.HasKey("OwnerId", "IsChar", "DataType");

                    b.ToTable("account_data", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.Character", b =>
                {
                    b.Property<uint>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("guid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Guid"));

                    b.Property<uint>("AccountId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("account_id");

                    b.Property<byte>("ActionBars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("action_bars");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("class");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte>("Face")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("face");

                    b.Property<byte>("FacialHair")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("facial_hair");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("gender");

                    b.Property<byte>("HairColor")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("hair_color");

                    b.Property<byte>("HairStyle")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("hair_style");

                    b.Property<byte>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("level");

                    b.Property<uint>("Map")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("map");

                    b.Property<uint>("Money")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1000000u)
                        .HasColumnName("money");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("name");

                    b.Property<float>("PositionX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("position_x");

                    b.Property<float>("PositionY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("position_y");

                    b.Property<float>("PositionZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("position_z");

                    b.Property<byte>("Race")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("race");

                    b.Property<byte>("Skin")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("skin");

                    b.Property<uint>("TalentResetCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("talent_reset_cost");

                    b.Property<uint>("Xp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("xp");

                    b.Property<uint>("Zone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("zone");

                    b.HasKey("Guid");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_characters_account");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_characters_name");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.CharacterActionButton", b =>
                {
                    b.Property<uint>("OwnerGuid")
                        .HasColumnType("int unsigned")
                        .HasColumnName("owner_guid");

                    b.Property<byte>("Button")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("button");

                    b.Property<uint>("PackedData")
                        .HasColumnType("int unsigned")
                        .HasColumnName("packed_data");

                    b.HasKey("OwnerGuid", "Button");

                    b.ToTable("character_action", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.CharacterAura", b =>
                {
                    b.Property<uint>("OwnerGuid")
                        .HasColumnType("int unsigned")
                        .HasColumnName("owner_guid");

                    b.Property<uint>("Spell")
                        .HasColumnType("int unsigned")
                        .HasColumnName("spell");

                    b.Property<byte>("Form")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("form");

                    b.Property<uint>("RemainingMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("remaining_ms");

                    b.HasKey("OwnerGuid", "Spell");

                    b.HasIndex("OwnerGuid")
                        .HasDatabaseName("ix_aura_owner");

                    b.ToTable("character_aura", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.CharacterItem", b =>
                {
                    b.Property<uint>("ItemGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("item_guid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("ItemGuid"));

                    b.Property<byte>("Bag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)255)
                        .HasColumnName("bag");

                    b.Property<uint>("ItemEntry")
                        .HasColumnType("int unsigned")
                        .HasColumnName("item_entry");

                    b.Property<uint>("OwnerGuid")
                        .HasColumnType("int unsigned")
                        .HasColumnName("owner_guid");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("slot");

                    b.Property<uint>("StackCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("stack_count");

                    b.HasKey("ItemGuid");

                    b.HasIndex("OwnerGuid")
                        .HasDatabaseName("ix_items_owner");

                    b.ToTable("character_items", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.CharacterQuestStatus", b =>
                {
                    b.Property<uint>("OwnerGuid")
                        .HasColumnType("int unsigned")
                        .HasColumnName("owner_guid");

                    b.Property<uint>("QuestId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("quest_id");

                    b.Property<ushort>("Counter0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("counter0");

                    b.Property<ushort>("Counter1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("counter1");

                    b.Property<ushort>("Counter2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("counter2");

                    b.Property<ushort>("Counter3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)0)
                        .HasColumnName("counter3");

                    b.Property<byte>("Slot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("slot");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.HasKey("OwnerGuid", "QuestId");

                    b.HasIndex("OwnerGuid")
                        .HasDatabaseName("ix_qs_owner");

                    b.ToTable("character_queststatus", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.CharacterSpell", b =>
                {
                    b.Property<uint>("OwnerGuid")
                        .HasColumnType("int unsigned")
                        .HasColumnName("owner_guid");

                    b.Property<uint>("Spell")
                        .HasColumnType("int unsigned")
                        .HasColumnName("spell");

                    b.HasKey("OwnerGuid", "Spell");

                    b.HasIndex("OwnerGuid")
                        .HasDatabaseName("ix_spell_owner");

                    b.ToTable("character_spell", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.CharacterTalent", b =>
                {
                    b.Property<uint>("OwnerGuid")
                        .HasColumnType("int unsigned")
                        .HasColumnName("owner_guid");

                    b.Property<uint>("TalentId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("talent_id");

                    b.Property<byte>("Rank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("rank");

                    b.HasKey("OwnerGuid", "TalentId");

                    b.HasIndex("OwnerGuid")
                        .HasDatabaseName("ix_talent_owner");

                    b.ToTable("character_talent", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.DeclinedName", b =>
                {
                    b.Property<uint>("OwnerGuid")
                        .HasColumnType("int unsigned")
                        .HasColumnName("owner_guid");

                    b.Property<string>("N0")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasDefaultValue("")
                        .HasColumnName("n0");

                    b.Property<string>("N1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasDefaultValue("")
                        .HasColumnName("n1");

                    b.Property<string>("N2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasDefaultValue("")
                        .HasColumnName("n2");

                    b.Property<string>("N3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasDefaultValue("")
                        .HasColumnName("n3");

                    b.Property<string>("N4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasDefaultValue("")
                        .HasColumnName("n4");

                    b.HasKey("OwnerGuid");

                    b.ToTable("character_declined_names", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.Realm", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("address");

                    b.Property<byte>("Flags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("flags");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<float>("Population")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("population");

                    b.Property<ushort>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasDefaultValue((ushort)8085)
                        .HasColumnName("port");

                    b.Property<byte>("Timezone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("timezone");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_realmlist_name");

                    b.ToTable("realmlist", (string)null);
                });

            modelBuilder.Entity("AlexWoW.Database.Entities.TeleportLocation", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<byte>("Faction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("faction");

                    b.Property<uint>("Map")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("map");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<float>("O")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("o");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<float>("X")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("x");

                    b.Property<float>("Y")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("y");

                    b.Property<float>("Z")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("z");

                    b.Property<uint>("Zone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.ToTable("dev_teleport", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
